### PR TITLE
Fix Javascript check for Yoast

### PR DESCRIPTION
**Pull request by pjrobertson**
Fix bug with certain plugins where this code loads but YoastSEO isn't available.

Some pages seemed to be loading the qwpseo-exec script, even though Yoast wasn't being loaded.

I'm not quite sure of the underlying issue, but this is a quick fix that will solve this problem short of the complete re-coding that the Yoast module needs. This just checks that window.YoastSEO exists first.

### CODE REVIEW

**Comment by herrvigg** [comment]
> Some pages seemed to be loading the qwpseo-exec script, even though Yoast wasn't being loaded.

In fact that doesn't sound good, this script should not be loaded at all in that case. Will check better to see if i find something.

**Comment by herrvigg** [comment]
@pjrobertson but currently the Yoast module is still disabled. How did you enable it again, just uncommented the related block in qtx_modules_handler.php? You should also deactivate/activate qTranslate-XT, otherwise the Yoast plugin status might not be updated.

**Comment by pjrobertson** [comment]
Yes, that's what I did @herrvigg. Noted on the deactivate/activate process, it's been working find for the past 6 months!

**Comment by herrvigg** [comment]
In fact, this is not normal. The script should never be called if the Yoast script is not loaded, because there is dependency to `yoast-seo-post-scraper` or `yoast-seo-term-scraper`. 

The fix should be fine to get around this but I would like to be able to reproduce this to understand. Could you try to isolate the case (minimum number of plugins) and the page where this happens?

**Comment by herrvigg** [comment]
@pjrobertson any update?

**Comment by herrvigg** [comment]
Let's merge this change, it doesn't cost much. Anyway more work is needed to make Yoast work again, see #794.

**Comment by herrvigg** [comment]
Merged after fixing the conflict locally.

**Pull request closed without merging**
