### PR TITLE
QTS: Bugfix to make it work correctly on pages

### PR DESCRIPTION
**Pull request by sviluppomania**
https://github.com/not-only-code/qtranslate-slug/pull/125

### CODE REVIEW

**Comment by herrvigg** [comment]
I don't know the code well enough to approve this patch yet.
More explanations are needed, also to understand the issue better. Strange no one participating to #671 mentioned this problem.
Finally the author commented the fix as "probably an ugly one", it's an indication it should be improved.
If there is an issue can you describe how to reproduce it?

**Comment by spleen1981** [comment]
Pages slugs are working just fine. Maybe it was a workaround to some issue solved in the meantime? original PR mentioned is from 2016...

**Comment by sviluppomania** [comment]
@spleen1981 @herrvigg 
One of the qtranslate-slug contributors, [@LC43](https://github.com/LC43), is still active. You could ask him to cooperate.

https://github.com/not-only-code/qtranslate-slug/commit/386b90723d79792ffe4b88138908a065e82b01f2

**Comment by spleen1981** [comment]
Sure, anyone's contribution is welcome I guess.
But as this is your PR, I assume you should clarify what is the reason to merge a "probably ugly" commit if there is not any clear bug to be fixed (or at least not reported yet).

**Pull request closed without merging**
