### PR TITLE
Removes enforcement of suppress filters=false

### PR DESCRIPTION
**Pull request by Bones5**
https://github.com/qTranslate-Team/qtranslate-x/pull/433/commits/b8146a1be459bd7b08ec6ace3ff7bb2954a29511

https://github.com/qtranslate/qtranslate-xt/issues/433

### CODE REVIEW

**Comment by Bones5** [comment]
Ok yes I see that, PR rewritten.

Yes it probably was there for a reason, I will try and investigate. 

It appears to just re-enforce the default and prevent you from using `suppress_filters` in your code. This can make it difficult to select the language you want programatically, I currently want to construct an object with both languages to pass to a search index. I have had similar issues trying to pass an object to JS for animation

**Comment by Bones5** [comment]
I have managed to do a bit of testing on this today, so far I have found one effect of the change:

When using `get_field` on an ACF Post Object the `post_title` is now returned without filters. This is actually a more consistent response as `post_content` has always been returned without filters being applied, we typically use `apply_filters` on the content but not on the title.

There doesn't appear to be any change in the behaviour of a standard `get_posts()` or `WP_Query`, I'm unable to understand why `get_field()` is not working in the same way so cannot offer a fix for backwards compatibility.

This does currently make this a breaking change but again provides a more consistent experience that allows the developer to apply filters at their discretion.

I still believe this is a worthwhile change as given the progress towards JS and React in WordPress, the ability to pass multiple translations of strings to services outside of PHP and the current language is becoming more useful. It also prevents the undesired override of a standard WordPress feature

**Comment by herrvigg** [comment]
The specific case for the `nav_menu_item` came in qTranslate-X release 3.3.3. I found some discussions about this `pre_get_posts` filter here:
https://wordpress.org/support/topic/menu-conflict-with-plugin-custom-field-template/page/3/

> commenting out 331, cannot be a permanent solution, since it will break many other sites, although it is a very valuable information to know that it conceals your problem.

The row number changed but for sure it is equivalent to remove this `suppress_filter=false` override. I don't really understand what was meant with "it will break many other sites"... 😕

**Comment by Bones5** [comment]
I've realised that the `post_content_ml` and `post_title_ml` fields actually perform the function I'm looking for.

It feels that this function could be ensuring compatibility with other plugins and there are too many unknown effects for it to be removed

**Comment by herrvigg** [comment]
Great you find a way to solve this! 
I'm still not sure about the effect of removing the filter override entirely. Once we move to the next repo i will try to remove it and restart from scratch, we'll see better what we really need to keep.

**Pull request closed without merging**
