### PR TITLE
Support for translation of gform_savecontinue_link

### PR DESCRIPTION
**Pull request by reddo**
These are some changes I've made to that file if I'm not wrong.

### CODE REVIEW

**Comment by herrvigg** [comment]
Yes that's the good file, i trust you on that change since it's entirely specific to gravity forms.

**Comment by reddo** [comment]
I'll try and review the branch again this afternoon. Could you update this branch with the changes from `master`? I think it's behind with a few commits.

**Comment by herrvigg** [comment]
@reddo i've just rebased the branch on master to get the last commits.

**Comment by reddo** [comment]
@herrvigg Excellent, I'll give it a try as soon as I can.

**Pull request merged**
